name: ci
on: push
jobs:
  # example splitting all tests across GitHub machines
  prepare:
    runs-on: ubuntu-20.04
    # explicitly set the output of this job
    # so that other jobs can use it
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      # generate the list using a bash script
      - name: Create matrix ⊹
        id: prepare
        # for reusable workflow, must use the full action reference
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 3 # number of containers to output

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

  test-spec:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1, 2]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Run split Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        # using operating system process environment variables
        env:
          SPEC: 'cypress/e2e/add-recipe.js,cypress/e2e/examples/traversing-elements.js,cypress/e2e/testHeader.js,cypress/e2e/examples/datepicker.js,cypress/e2e/testHomePage.js,cypress/e2e/search-recipe.js,cypress/e2e/testSearchResults.js,cypress/e2e/examples/mouse-actions.js,cypress/e2e/testSearch.js'
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
