name: Cypress Automation Tests
on: [push]
jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: install playwright
        run: npx playwright install-deps webkit
      - name: Run Tests
        run: npx cypress run --env allure=true --spec $(node cypress-parallel.js ${{ matrix.containers }} 5) --browser chrome
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        if: always()
        with:
          name: ReportsData
          path: allure-results
